user type in logged user endpoint
e-Stella-AGH/RecruitmentService pull request #34
Opened 2021-07-08 19:16 UTC by Davenury

2021-07-08 20:07 UTC, Davenury commented
https://stackoverflow.com/questions/43344819/reading-response-headers-with-fetch-api?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa -> jakby się ktoś zastanawiał, dlaczego token w body, nie headerach. TL;DR - cors ma ograniczenia na headery

2021-07-08 20:09 UTC, Rados13 reviewed
Czemu tego nie przesyłamy w takim razie jako json z dwoma wartościami tylko jako stringa oddzielonego przecinkiem i potem na froncie będziemy musieli robić splita?

2021-07-08 20:11 UTC, Davenury commented
> Czemu tego nie przesyłamy w takim razie jako json z dwoma wartościami tylko jako stringa oddzielonego przecinkiem i potem na froncie będziemy musieli robić splita?

A jakoś tak mi wyszło, bo klasa token dziedziczy po OneStringValueMessage i już nie bardzo chciało mi się zmieniać XDD ogólnie mogę zmienić jutro, ale front jest już pod to podpięty XDDD

2021-07-09 23:04 UTC, Pinioo requested changes

2021-07-10 19:12 UTC, closed without merging