Es 162
e-Stella-AGH/RecruitmentService pull request #73
Opened 2021-11-03 21:50 UTC by tomros766

2021-11-04 18:09 UTC, Davenury commented on src/main/kotlin/org/malachite/estella/mails/Payloads.kt
> +    val url = "${MAIN_URL}task_stage/${this.id}/${offer.creator.organization.id}"
Wydaje mi się, że ten url jest zły XDD
Zwłaszcza że ten widoczek musi mieć zakodowanego base64 maila, czego tutaj nie widać. Pamiętaj, że to nie jest link do RSa, tylko do Main Front Appa, a ja go pisałem jakoś tak:
mainURL/tasks/assign/{organizationUUID}/{devMailBase64}

2021-11-04 18:09 UTC, Davenury commented on src/main/kotlin/org/malachite/estella/services/ApplicationService.kt
> +    private fun Application.addNewApplicationStageData(recruitmentStage: RecruitmentStage, devs: MutableList<String>?) =
Nie łatwiej byłoby Ci to robić na pustej liście? Zamiast na nullowalnej liście?

2021-11-04 18:09 UTC, Davenury commented on src/main/kotlin/org/malachite/estella/services/ApplicationStageDataService.kt
> +                                ?.let { it.user == hrPartner.user }
Letów nie musisz zagnieżdżać, ale jest to pierdoła, więc git

2021-11-04 18:09 UTC, Davenury commented on src/main/kotlin/org/malachite/estella/services/TaskStageService.kt
> +    fun getTasksByOrganizationUuid(organizationUuid: String) =
Pytanie Radka, ale czy nie powinniśmy tu UUID używać?

2021-11-04 18:09 UTC, Davenury commented on src/main/kotlin/org/malachite/estella/services/TaskStageService.kt
> +        checkDevPassword(organizationUuid, password)
Wiem, że tak pisaliśmy wcześniej, dlatego nie musisz, ale możesz:
czy nie lepiej byłoby `assertDevPasswordIsCorrect`?

2021-11-04 20:12 UTC, Pinioo requested changes
Te Stringi na UUID bym pozamieniał tak jak Pan Radek powiedział

2021-11-04 20:12 UTC, Pinioo commented on src/main/kotlin/org/malachite/estella/task/api/TaskController.kt
> +                            ?:let{
tutaj ten let jest niepotrzebny, a wgl całe to wyrażenie `?: ...` można by było wynieść poza tego aktualnego leta (ale to już taki przypisek redakcji)

2021-11-04 20:12 UTC, Pinioo commented on src/main/kotlin/org/malachite/estella/task/api/TaskController.kt
> +    }
Można tu spróbować wyjść z `if (cond) true else false`, zapakować w jakąś listę booli i zrobić `.all { it }` na przykład

2021-11-04 20:12 UTC, Pinioo commented on src/main/kotlin/org/malachite/estella/task/api/TaskStageController.kt
> +            taskStageService.checkDevPasswordFromInterviewUuid(it!!, password)
to `!!` możesz już zrobić na `interviewUuid`

2021-11-04 20:12 UTC, Pinioo commented on src/test/kotlin/org/malachite/estella/queue/TaskResultTest.kt
> +    private fun send(msg: Map<String, String?>) = Json.encodeToString(msg).let {
Po co tutaj nullable string?

2021-11-07 10:38 UTC, Davenury approved these changes

2021-11-08 08:58 UTC, Pinioo approved these changes

2021-11-08 09:01 UTC, merged