[fix-taskresult-bug]
e-Stella-AGH/RecruitmentService pull request #89
Opened 2021-11-27 15:04 UTC by Pinioo

startTask had been using wrong (data class specific) TaskResult#copy method with named parameters

2021-11-27 15:38 UTC, Rados13 requested changes
Potężny bugfix nie przechodzi CI @Pinioo

2021-11-27 15:52 UTC, Pinioo commented
> Potężny bugfix nie przechodzi CI @Pinioo

Wim, fixane było, teraz powinno być git

2021-11-28 15:19 UTC, tomros766 approved these changes

2021-11-28 16:27 UTC, Pinioo commented
Metody kopiujące w innych data classach też sprawiały problemy, przepisane w inny sposób, żeby było dobrze

2021-11-28 16:29 UTC, tomros766 approved these changes

2021-11-29 19:41 UTC, Rados13 requested changes
Ogólnie Kotlin używa do equals, hashCode i toString tylko parametrów z głównego konstruktora, więc nie do końca ogarniam jaki jest sens tych zmian poza tym że w kij wyglądają jakby robił je ktoś kto klepał głównie w Javie XDD

2021-11-29 19:41 UTC, Rados13 commented on src/main/kotlin/org/malachite/estella/commons/models/offers/Application.kt
> +    fun getCurrentApplicationStage(): ApplicationStageData = this.applicationStages.sortedBy { it.id }.last()
Jaki jest sens robienie klasy pomocniczej do obsługi hashCode, skoro hashCode jest robione tylko z pól w głównym constructorze?

2021-11-30 17:43 UTC, Rados13 approved these changes

2021-11-30 17:44 UTC, Davenury approved these changes

2021-11-30 17:48 UTC, merged